todo_subject/todo_board/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='todo_board'

urlpatterns=[
    url(r'^$', views.Todo_board.as_view(), name='todo_board'),
    url(r'^insert/$', views.check_post, name='todo_board_insert'),
    # pk는 게시판 고유 번호 즉, 고유번호/detail url로 들어가면 고유번호에 따른 게시판을 상세보기로 볼 수 있음.
    url(r'^(?P<pk>[0-9]+)/detail/$', views.Todo_board_detail.as_view(), name='todo_board_detail'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.Todo_board_update.as_view(), name='todo_board_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.Todo_board_delete.as_view(), name='todo_board_delete'),
    #url(r'^board/insert/$', views.Todo_insert.as_View(), name='todo_board'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

todo_subject/todo_main/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='todo_main'

urlpatterns=[
    url(r'^$', views.Todo_main.as_view(), name='todo_main'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

todo_subject/todo_subject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_main.urls')),
    path('index/', include('todo_main.urls')),
    path('home/', include('todo_main.urls')),

    # board app
    path('board/', include('todo_board.urls')),
]

todo_subject/todo_board/models.py
from django.db import models

# Create your models here.

class ProjectCode(models.Model):
    pcode = models.CharField(db_column='PCODE', primary_key=True, max_length=4)  # Field name made lowercase.
    pname = models.CharField(db_column='PNAME', max_length=100)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'project_code'


class TodoList(models.Model):
    no = models.AutoField(db_column='No', primary_key=True)  # Field name made lowercase.
    pcode = models.CharField(db_column='PCODE', max_length=4)  # Field name made lowercase.
    user_id = models.CharField(db_column='USER_ID', max_length=50, blank=True, null=True)  # Field name made lowercase.
    title = models.CharField(db_column='TITLE', max_length=200, blank=True, null=True)  # Field name made lowercase.
    content = models.CharField(db_column='CONTENT', max_length=1000, blank=True, null=True)  # Field name made lowercase.
    is_complete = models.IntegerField(db_column='IS_COMPLETE', blank=True, null=True)  # Field name made lowercase.
    priority = models.IntegerField(db_column='PRIORITY', blank=True, null=True)  # Field name made lowercase.
    end_date = models.DateField(db_column='END_DATE', blank=True, null=True)  # Field name made lowercase.

    def todo_save(self):
        self.save()

    class Meta:
        managed = False
        db_table = 'todo_list'

todo_subject/todo_main/models.py
from django.db import models

# Create your models here.

todo_subject/todo_board/forms.py
from django import forms
from .models import TodoList

# date input type을 date로 설정 --> 달력 뜨게함.
class DateInput(forms.DateInput):
    input_type = 'date'

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('title', 'content', 'end_date')
        widgets = {
            # end_date ==> dateInput 클래스 불러옴.
            'end_date' : DateInput()
        }

todo_subject/todo_board/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import TodoList
from .forms import TodoForm
from datetime import datetime

# board view
class Todo_board(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        # todo_main에 있는 템플릿 폴더에서 해당 html을 찾으시오.
        template_name = 'todo_board/todo_board_list.html'
        # 기한이 없는 일정, 마감 안된 일정 --> 모든 객체를 가져옴.
        todo_list_no_endDate = TodoList.objects.all().filter(end_date__isnull=True, is_complete=0).order_by('priority')
        #기한 있고, 마감이 안된 애들
        todo_list_endDate_non_complete = TodoList.objects.all().filter(end_date__isnull=False, is_complete=0).order_by('priority')
        #마김이 된 애들
        todo_list_endDate_complete = TodoList.objects.all().filter(is_complete=1).order_by('end_date')
        today = datetime.now()
        # 마감이 가까운 일정
        close_end_day = []
        # 마감이 지난 일정
        over_end_day = []
        for i in todo_list_endDate_non_complete:
            e_day = str(i.end_date).split("-")
            end_day = datetime(int(e_day[0]), int(e_day[1]), int(e_day[2]))
            if (end_day - today).days < -1: over_end_day.append(i.title)
            if (end_day - today).days >= -1 and (end_day - today).days < 3: close_end_day.append(i.title)
        return render(request, template_name, {"todo_list_endDate_non_complete": todo_list_endDate_non_complete, "todo_list_endDate_complete": todo_list_endDate_complete, "todo_list_no_endDate": todo_list_no_endDate, 'close_end_day': close_end_day, 'over_end_day':over_end_day})


# generic.DetailView를 이용하면 굉장히 편하게 상세보기 페이지를 만들 수 있음.
class Todo_board_detail(generic.DetailView):
    model = TodoList
    template_name = 'todo_board/todo_board_detail.html'
    context_object_name = 'todo_list' # context_object_name은 해당 object의 이름을 설정. template에서 저 이름을 가지고 접

def check_post(request):
    template_name = 'todo_board/todo_board_success.html'
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            message = "일정을 추가하였습니다."
            todo.todo_save()
            return render(request, template_name, {"message": message})
    else:
        template_name = 'todo_board/todo_board_insert.html'
        form = TodoForm
        return render(request, template_name, {'form' : form})

class Todo_board_update(generic.UpdateView):
    model = TodoList
    fields = ('title', 'content', 'end_date')
    template_name = 'todo_board/todo_board_update.html'
    # success_url 은 업데이트 성공 시 이동하는 url
    success_url = '/board/'

    # save 기능
    def form_valid(self, form):
        form.save()
        return render(self.request, 'todo_board/todo_board_success.html', {"message":"일정을 업데이트 하였습니다."})

    # form 데이터 받아오는 기능
    def get(self, request, *args, **kwargs):
        # 오브젝트를 받아와서 폼 클래스를 받아온 후 이것을 return 해줘야 한다.
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)

class Todo_board_delete(generic.DeleteView):
    model = TodoList
    success_url = '/board/'
    context_object_name = 'todo_list'

todo_subject/todo_main/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import generic
from django.views import View

class Todo_main(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'todo_main/index.html'
        return render(request, template_name)

todo_subject/todo_board/templates/todo_board/todo_board_detail.html
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
<section id='blog'>
  <div class='container'>
      {{ todo_list }}
    <h2>{{ todo_list.title }}</h2>
    <p>{{ todo_list.content | linebreaksbr }}</p><br>
    <h2><a href="{% url 'todo_board:todo_board_update' pk=todo_list.pk %}">수정</a></h2>
    <h2><a href="{% url 'todo_board:todo_board_delete' pk=todo_list.pk %}">삭제</a></h2>
  </div>
</section>

{% endblock main %}

todo_subject/todo_board/templates/todo_board/todo_board_insert.html
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
<!-- Model body -->
<div class="col-md-12">
  <div class="container">
    <form method="POST" class="post-form" action="{% url 'todo_board:todo_board_insert' %}">
      <!-- 데이터가 보안상 잘 가져오도록 지원 -->
      <!-- csrf : '사이트 간 요청 위조'라는 웹사이트 공격 중 하나를 말함 -->
      {% csrf_token %}

      {{form.as_p}}
      <button type="submit" class="save btn btn-default">Save</button>
    </form>
  </div>
</div>

{% endblock main %}

todo_subject/todo_board/templates/todo_board/todo_board_list.html
{% extends 'todo_main/common/header.html' %}
{%load static%}
{% block main %}

<div class="alert alert-info">
    <strong>마감이 지난 일정!</strong> {{ over_end_day }}
</div>
<div class="alert alert-info">
    <strong>마감이 가까운 일정!</strong> {{ close_end_day }}
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 있는 일정</h2><br>
        <div id="todo_list_endDate" class="list-group col">
            {% for list in todo_list_endDate_non_complete %}
            <div class="list-group-item" div_pk={{list.no}} priority={{list.priority}}><input type="checkbox" pk={{list.no}} name="end_non_complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 없는 일정</h2><br>
        <div id="todo_list_no_endDate" class="list-group col">
        {% with end_date="마감일 없음" %}
            {% for list in todo_list_no_endDate %}
            <div class="list-group-item" div_pk={{list.no}}><input type="checkbox" pk={{list.no}} name="no_endDate_non_complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{end_date}}</p></div>
            {% endfor %}
        {% endwith %}
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="container">
        <h2>마감 된 일정</h2><br>
        <div class="list-group col">
            {% with end_date="마감일 없음" %}
                {% for list in todo_list_endDate_complete %}
                    {% if list.end_date == None %}
                        <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.no}} name="complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{end_date}}</p></div>
                    {% else %}
                        <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.no}} name="complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
                    {% endif %}
                {% endfor %}
            {% endwith %}
        </div>
    </div>
</div>
<div>
  <button type='button' class='btn btn-primary' onclick="location.href='{% url 'todo_board:todo_board_insert' %} '">
    글쓰기
  </button>
</div>
</div>
</div>

{% endblock main %}

todo_subject/todo_board/templates/todo_board/todo_board_success.html
<script>
  message = "{{ message }}";
  console.log(message);
  alert(message);
  window.location.href = "{% url 'todo_board:todo_board' %}"
</script>

todo_subject/todo_board/templates/todo_board/todo_board_update.html
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}

       {{form.as_p}}
       <input type="submit" class="save btn btn-default" value="Update"></input>
   </form>
  </div>
</section>

{% endblock main %}

todo_subject/todo_board/templates/todo_board/todolist_confirm_delete.html
{% extends 'todo_main/common/header.html' %}
{% load static %}
{% block main %}
<section id='blog'>
<div class='container'>
  <form method="POST" class='post-form'>
    {% csrf_token %}
    <p> 정말로 {{todo_list.title}} 를 삭제하시겠습니까 ? </p>
  <input type="submit" class="save btn btn-default" value='Confirm'/>
  </form>
</div>
</section>

{% endblock main %}

todo_subject/todo_main/templates/todo_main/common/header.html
<html lang="ko">

    {% load static %}
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--Fontawesom-->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!--Animated CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">

        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!--Bootstrap Carousel-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/carousel.css' %}" />

        <link rel="stylesheet" href="{% static 'css/isotope/style.css' %}">

        <!--Main Stylesheet-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <!--Responsive Framework-->
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script>



        </script>
		<style type="text/css">
            #container {
                min-width: 310px;
                max-width: 800px;
                height: 400px;
                margin: 0 auto
            }
            input[type=text] {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              box-sizing: border-box;
            }

            .list-group-item{
                width : 40%;
            }
		</style>


    </head>
    <body>
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#"></a>
            </div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'todo_main:todo_main' %}">todo main</a></li>
              <li><a href="{% url 'todo_board:todo_board' %}">todo list</a></li>
            </ul>
          </div>
        </nav>
        {% block main %}

        {% endblock main %}
    </body>
</html>

todo_subject/todo_main/templates/todo_main/index.html
<!-- 상속 -->
{% extends 'todo_main/common/header.html' %}
<!-- static 폴더와 연결 -->
{% load static %}

<!-- 상속한 파일에 아래 코드 연결 -->
{% block main %}

<div class='col-md-12'>
  <div class='container'>
    <center>
      <h1>todo 메인화면입니다.</h1>
    </center>
    <p></p>
  </div>
</div>
{% endblock main %}